### ISSUE TITLE
[OpenMRS] Amqp Integration

### ISSUE THREAD

**Issue by am2990** [am2990/chs-iiitd#5]
Provide integration with Spring AMQP rather than JAVA POJO's and Threads

http://projects.spring.io/spring-amqp/

**Comment by anam-s** [comment]
OK.I'll let u know when it is done.hopefully in a day or 2

**Comment by am2990** [comment]
Anam this is an OpenMRS feature which Komal will be implementing and it's assigned to her.

You only need to look into the issues assigned to you.

**Comment by anam-s** [comment]
OK.I saw all the mails.I'll do the ones assigned to me
